### ISSUE TITLE
<esc> should exit fnr after having pressed <tab>

### ISSUE THREAD

**Issue by lydell** [junegunn/vim-fnr#2]
1. Open fnr, for example with `<leader>re`.
2. Press `<tab>` to choose flags.
3. Press `<esc>`.

Actual: Nothing happens.
Expected: fnr is closed.

Seems like the only way to get out of there is to press `<tab>` and then press `<esc>`.

**Comment by junegunn** [comment]
Thanks. Fixed it.

**Comment by junegunn** [comment]
Thanks. Fixed it.
