### ISSUE TITLE
Make fnr flags display more user friendly

### ISSUE THREAD

**Issue by lydell** [junegunn/vim-fnr#3]
Even though the flags are mnemonics and pretty easy to remember, every now and then I get a brain-freeze and just can’t think of the letter to press in order to use the flag I’m looking for.

What about instead of showing an `_` for inactivated flags we’d show the actual letter but in another color? We could also use casing: Uppercase=disabled, lowercase=enabled.

This would also make fnr even more friendly to new vim users.

**Comment by junegunn** [comment]
Just realized that I implemented just the opposite of your suggestion, But I think it's good enough for now.

> This would also make fnr even more friendly to new vim users.

fnr is one of my plugins that I do not really care about attracting users. I know it, I use it, and I like it. That's all I need :)

**Comment by lydell** [comment]
Thanks!
