### ISSUE TITLE
Regex mode?

### ISSUE THREAD

**Issue by lydell** [junegunn/vim-fnr#4]
Even though I love that the search and replace of fnr uses literal strings, I sometimes want to use a regex search. Then it sucks having to use the old `%s/a/b/g` or whatever.

I propose adding an `r` flag to toggle regex mode. When hitting `<enter>` to type in the replacement, the replacement string should be initially empty, since the regex might match several strings. Instead, we can use `&` etc.

What do you think?

**Comment by junegunn** [comment]
Thanks for the suggestion but I think it's beyond the scope of this plugin. IMO, `:s` is better for complex substitution needs. You might want to check out vim-over if you need substitution preview.

https://github.com/osyo-manga/vim-over
